[project]
name = "mcp-searxng"
version = "0.1.0"
description = "MCP server for connecting agentic systems to search systems via searXNG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.1.2",
    "pydantic>=2.10.3",
]
